<?php


namespace Bridge;


class FoldedPhone extends Phone
{
    public function open()
    {
        parent::open(); // TODO: Change the autogenerated stub

        printf("折叠样式手机\n");
    }

    public function close()
    {
        parent::close(); // TODO: Change the autogenerated stub

        printf("折叠样式手机\n");
    }

    public function call()
    {
        parent::call(); // TODO: Change the autogenerated stub

        printf("折叠样式手机\n");
    }
}